### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by n3o33** [Th3C0D3R/FoBJS#10]
on windows: just a black screen after log in. no gui visible

on linux:  a second display appears, both black screen and this error
![image](https://user-images.githubusercontent.com/54777488/90879790-b8576400-e3a7-11ea-9d3c-50b6269460d9.png)

**Comment by lehoangthanh** [comment]
@n3o33 
You should delete:
 folder "rm -rf  ~/.config/Forge\ of\ Bots\ JS/"
"rm rf ~/.cache/fo..." you tab to show full name as "fobjs_linux"
