### ISSUE TITLE
Fobjs_windows (Java script error)

### ISSUE THREAD

**Issue by befire007** [Th3C0D3R/FoBJS#12]
Which Server are you playing on (de/en/beta(zz)/...): en
What OS you run: windows 10 enterprise
Are there any errors on the screen: yes below
(a javascript error occured in the main process
uncaught SyntaxError: Unexpected end of JSON input at JSON.parse (anonymous )
at object.anonymous<> D:\Program Files\Forge Of Empires Application\fobjs_windows\fobjs-win32-x64\resources\app.asar\main.js;141:19)

NB: first time run work perfect than after a while it freeze then each run give this error.

**Comment by Th3C0D3R** [comment]
Delete every json inside the "appdata/roaming/Forge of Bots Js" folder (or the entire folder if this does not work)
Should then work

**Comment by befire007** [comment]
10x this work fine.

why Recurring-quest and tavern and aid and incident Bot are showing unavailable? i toggle all bots on.

Best Regards

Khaled Al Ali.
Senior IT Officer
Mb: +961-3134188
E-Mail: Befire@live.com
________________________________

**Comment by Th3C0D3R** [comment]
They are unavailable because I did not implement them. 
Also if it still does not work, try to delete the ForgeHX....js inside the "appdata/roaming" folder

**Comment by befire007** [comment]
yea it work great now thank you.

when you will gonna implement all bots ?
the bots not collection Gold from houses or soliders production too.
could i sign in in my browser and the bots in same time (to collect gold and soliders and fight in guild?)
Khaled Al Ali.
Senior IT Officer
Mb: +961-3134188
E-Mail: Befire@live.com
________________________________

**Comment by befire007** [comment]
yea it work great now thank you.

when you will gonna implement all bots ?
the bots not collection Coins from houses or soldier's production too.
could i sign in in my browser and the bots in same time (to collect coins and soldiers and fight in guild?)


Khaled Al Ali.
Senior IT Officer
Mb: +961-3134188
E-Mail: Befire@live.com
________________________________

**Comment by Th3C0D3R** [comment]
They will not be implemented in the javascript version bit i am working on a c# version which will be better in everything.

Also you cant login both from browser and bot at the same time.

Building should be collected as soon as you press collect manually or after the supplys are ready to collect

**Comment by befire007** [comment]
Thank you awaiting your C# version
best regards

Khaled Al Ali.
Senior IT Officer
Mb: +961-3134188
E-Mail: Befire@live.com
________________________________

**Comment by Th3C0D3R** [comment]
Please use the new Bot here: [FoBCS](https://github.com/th3c0d3r/fobcs) v1.1.0
And delete the old one.
