### ISSUE TITLE
Auto Recruit

### ISSUE THREAD

**Issue by befire007** [Th3C0D3R/FoBJS#13]
Could you please add autorecruit soldiers to the bot 1.2.8 ?

**Comment by Th3C0D3R** [comment]
I will add it as soon as possible. But not in the near future

**Comment by Th3C0D3R** [comment]
Please use the new Bot here: [FoBCS](https://github.com/th3c0d3r/fobcs) v1.1.0
And delete the old one. 
Autorecruit will be added also as soon as its at the top of my todo list
