### ISSUE TITLE
Error when opening

### ISSUE THREAD

**Issue by xphantomdavex** [Th3C0D3R/FoBJS#14]
First Thank you for this its actually really cool and useful, but I let the bot run overnight, and now every time I open I get this error message, Just gonna redownload for now but that's kind of annoying, like Idk even know if it actually ran for more than a couple hours because when I woke up the program had crashed 

![image](https://user-images.githubusercontent.com/61061338/94812589-eecfc800-03c4-11eb-8afe-caea13d7ff68.png)

**Comment by xphantomdavex** [comment]
Saw the other issue and was able to fix the problem , Question tho after the bot was closed because of the error inside of task manager like 10 processes for the bot were running and I couldn't end them. IS this normal ?

**Comment by Th3C0D3R** [comment]
> Saw the other issue and was able to fix the problem , Question tho after the bot was closed because of the error inside of task manager like 10 processes for the bot were running and I couldn't end them. IS this normal ? 

No this should not be normal and those tasks are maybe instances which crashed but still running.

**Comment by xphantomdavex** [comment]
SO yeah um maybe its the way I'm closing it ? Because it hasn't crashed since I fixed it, also where'd you learn how to do this ? lol like I understand somewhat the language but Im still looking at this stuff like "wtf is going on"
![image](https://user-images.githubusercontent.com/61061338/94857281-425f0780-03ff-11eb-8e5e-b863ccf2151b.png)

**Comment by Th3C0D3R** [comment]
Please use the new Bot here: [FoBCS](https://github.com/th3c0d3r/fobcs) v1.1.0
And delete the old one.
