### ISSUE TITLE
Do you want help in c #

### ISSUE THREAD

**Issue by Dadoudu64** [Th3C0D3R/FoBJS#7]
I am a good programmer in .NET languages and I love what you do so I would like to help you with the development of a new FoB.

I can take care of the code or the design if you want to go faster.

Thank you for your reply.

**Comment by Th3C0D3R** [comment]
I am fine, thanks. Also good .Net programmer here. I will publish the sources as soon as its get to the current level of the JavaScript version

**Comment by Th3C0D3R** [comment]
Then you can contribute stuff :)

**Comment by Dadoudu64** [comment]
ok

**Comment by Th3C0D3R** [comment]
Its time, I didnt thought I would finish it this year, but the new bot is out [FoBCS](https://github.com/th3c0d3r/fobcs) v1.1.0
