### ISSUE TITLE
Can't download precompiled version

### ISSUE THREAD

**Issue by sakata-g** [Th3C0D3R/FoBJS#8]
Hello,
The link to download the version 1.2.8 not work .
And the version 1.2.6 can't run beacause the 1.2.8 is available in git.
Can you fix it please ? 

Thanks :)

**Comment by Th3C0D3R** [comment]
Maybe use this link:
[Link](https://github.com/Th3C0D3R/FoBJS/releases/tag/v1.2.8beta)

**Comment by sakata-g** [comment]
Thanks the new Link Work 👍
