### ISSUE TITLE
Error when i launch the exe

### ISSUE THREAD

**Issue by sakata-g** [Th3C0D3R/FoBJS#9]
Hello,
I used the bot yesterday he worked great.
But today after running it many times, he stopped with an error.
And now when i try to launch the "fobjs.exe" i have this error :

![image](https://user-images.githubusercontent.com/69845237/90627313-1b1bf480-e21c-11ea-8360-0df83c4d71b6.png)

I tried to delete the folder and download a new one but the error is still there.
The bot work on another computer .

There is any cache i can delete to fix that ?

Thank again for your Help :)

**Comment by Th3C0D3R** [comment]
Yes there is a cache.
Inside the appdata/roaming folder there is a "Forge of Bots JS" folder and a file called "ForgeHX-....js" delete both and start the bot again

**Comment by sakata-g** [comment]
Thanks it work now .
Can't found the fille called "ForgeHX-....js".
I renamed the folder "Forge of Bots JS" in appdata/roaming .

**Comment by Th3C0D3R** [comment]
You can just delete the folder because its old and outdated, maybe it has to be deleted after every update of Forge of Empires
